# List all biases entailed by failed assertions, at any area of the AI development pipeline?
PREFIX airo: <https://w3id.org/airo#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX earl: <http://www.w3.org/ns/earl#>
PREFIX : <https://example.org/ex#>

SELECT DISTINCT ?biastype WHERE {
    ?doc rdf:type :BiasAudit .
    ?doc :hasAssertion ?biasassertion .
    ?biasassertion earl:result ?testresult .
    ?testresult earl:outcome ?testoutcome .
    ?testoutcome rdf:type ?type .
    FILTER(?type IN (:FloatFail , :IntFail , earl:Fail))
    ?biasassertion :testsBias ?biastype
}