# Are there any bias audits where a test suite indicated racial bias (not just individual fairness metrics)?
PREFIX airo: <https://w3id.org/airo#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX : <https://example.org/ex#>

ASK WHERE {
    ?doc rdf:type :BiasAudit .
    ?doc :interpetedBias :GenderBias .
}
